# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git config user.email "azuredevops@microsoft.com" 
    git config user.name "Azure Pipelines"
    git remote set-url origin https://git:$(github_pat)@github.com/$(github_repo).git
    npm install
    npm run build
    npm run export
    touch out/.nojekyll
    npm run publish
  displayName: 'npm install and build and publish'
